# Generated by Django 4.0.10 on 2023-09-27 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=main_app.models.dynamic_upload_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='file',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fileupload',
            name='images',
            field=models.ManyToManyField(to='main_app.image'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
        ),
    ]
