# Generated by Django 4.0.10 on 2023-09-28 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_image_remove_fileupload_file_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
