# Generated by Django 4.0.10 on 2023-09-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_file_name_fileupload_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='user_name',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
