# Generated by Django 4.0.10 on 2023-09-28 09:38

from django.db import migrations, models
import main_app.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_fileupload_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=main_app.models.dynamic_upload_path)),
            ],
        ),
    ]
